name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t08&#45;01&#45;01
      id: t08-45-01-45-01
      uses: education/autograding-io-grader@v1
      with:
        test-name: t08&#45;01&#45;01
        setup-command: make compile
        command: make -s test_01
        input: |
          student-add#12S21001#Dhino Turnip#2021#male
          student-add#12S21002#Marudut Tampubolon#2021#male
          student-add#12S21003#Jusas Tampubolon#2021#male
          student-print-all
          student-add#12S21004#Estomihi pangaribuan#2021#male
          student-add#12S21006#Weny Sitinjak#2021#female
          student-add#12S21007#Dame Sitinjak#2021#female
          student-add#12S21008#Tuani Manurung#2021#male
          student-add#12S21009#Mikhael Pakpahan#2021#male
          student-add#12S21010#Bobby Siagian#2021#male
          student-add#12S21011#Aldi Simamora#2021#male
          student-print-all
          ---
        expected-output: |
          12S21001|Dhino Turnip|2021|male
          12S21002|Marudut Tampubolon|2021|male
          12S21003|Jusas Tampubolon|2021|male
          12S21001|Dhino Turnip|2021|male
          12S21002|Marudut Tampubolon|2021|male
          12S21003|Jusas Tampubolon|2021|male
          12S21004|Estomihi pangaribuan|2021|male
          12S21006|Weny Sitinjak|2021|female
          12S21007|Dame Sitinjak|2021|female
          12S21008|Tuani Manurung|2021|male
          12S21009|Mikhael Pakpahan|2021|male
          12S21010|Bobby Siagian|2021|male
          12S21011|Aldi Simamora|2021|male
        comparison-method: exact
        timeout: 10
        max-score: 20
    - name: t08&#45;01&#45;02
      id: t08-45-01-45-02
      uses: education/autograding-io-grader@v1
      with:
        test-name: t08&#45;01&#45;02
        setup-command: make compile
        command: make -s test_01
        input: |
          student-add#12S21001#Dhino Turnip#2021#male
          student-add#12S21002#Marudut Tampubolon#2021#male
          student-add#12S21003#Jusas Tampubolon#2021#male
          student-add#12S21006#Weny Sitinjak#2021#female
          student-add#12S21004#Estomihi pangaribuan#2021#male
          student-add#12S21007#Dame Sitinjak#2021#female
          student-add#12S21008#Tuani Manurung#2021#male
          student-print-all
          student-add#12S21009#Mikhael Pakpahan#2021#male
          student-add#12S21010#Bobby Siagian#2021#male
          student-add#12S21011#Aldi Simamora#2021#male
          student-print-all
          ---
        expected-output: |
          12S21001|Dhino Turnip|2021|male
          12S21002|Marudut Tampubolon|2021|male
          12S21003|Jusas Tampubolon|2021|male
          12S21006|Weny Sitinjak|2021|female
          12S21004|Estomihi pangaribuan|2021|male
          12S21007|Dame Sitinjak|2021|female
          12S21008|Tuani Manurung|2021|male
          12S21001|Dhino Turnip|2021|male
          12S21002|Marudut Tampubolon|2021|male
          12S21003|Jusas Tampubolon|2021|male
          12S21006|Weny Sitinjak|2021|female
          12S21004|Estomihi pangaribuan|2021|male
          12S21007|Dame Sitinjak|2021|female
          12S21008|Tuani Manurung|2021|male
          12S21009|Mikhael Pakpahan|2021|male
          12S21010|Bobby Siagian|2021|male
          12S21011|Aldi Simamora|2021|male
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t08&#45;02&#45;01
      id: t08-45-02-45-01
      uses: education/autograding-io-grader@v1
      with:
        test-name: t08&#45;02&#45;01
        setup-command: make compile
        command: make -s test_02
        input: |
          dorm-add#Pniel#20#female
          dorm-add#Kapernaum#20#male
          dorm-print-all
          dorm-add#Antiokia#20#male
          dorm-print-all
          ---
        expected-output: |
          Pniel|20|female
          Kapernaum|20|male
          Pniel|20|female
          Kapernaum|20|male
          Antiokia|20|male
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t08&#45;02&#45;02
      id: t08-45-02-45-02
      uses: education/autograding-io-grader@v1
      with:
        test-name: t08&#45;02&#45;02
        setup-command: make compile
        command: make -s test_02
        input: |
          dorm-add#Pniel#20#female
          dorm-add#Kapernaum#20#male
          dorm-print-all
          dorm-add#Antiokia#20#male
          dorm-add#Mamre#20#male
          dorm-add#Silo#20#male
          dorm-add#Mahanaim#20#male
          dorm-add#Nazaret#20#male
          dorm-print-all
          ---
        expected-output: |
          Pniel|20|female
          Kapernaum|20|male
          Pniel|20|female
          Kapernaum|20|male
          Antiokia|20|male
          Mamre|20|male
          Silo|20|male
          Mahanaim|20|male
          Nazaret|20|male
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: t08&#45;02&#45;03
      id: t08-45-02-45-03
      uses: education/autograding-io-grader@v1
      with:
        test-name: t08&#45;02&#45;03
        setup-command: make compile
        command: make -s test_02
        input: |
          student-print-all
          dorm-print-all
          student-add#12S21001#Dhino Turnip#2021#male
          student-add#12S21002#Marudut Tampubolon#2021#male
          student-add#12S21003#Jusas Tampubolon#2021#male
          student-add#12S21004#Estomihi pangaribuan#2021#male
          student-add#12S21006#Weny Sitinjak#2021#female
          student-add#12S21007#Dame Sitinjak#2021#female
          student-add#12S21008#Tuani Manurung#2021#male
          dorm-add#Pniel#20#female
          dorm-add#Kapernaum#20#male
          dorm-print-all
          student-add#12S21009#Mikhael Pakpahan#2021#male
          student-add#12S21010#Bobby Siagian#2021#male
          student-add#12S21011#Aldi Simamora#2021#male
          student-print-all
          dorm-add#Antiokia#20#male
          dorm-add#Mamre#20#male
          dorm-add#Silo#20#male
          dorm-add#Mahanaim#20#male
          dorm-add#Nazaret#20#male
          dorm-print-all
          ---
        expected-output: |
          Pniel|20|female
          Kapernaum|20|male
          12S21001|Dhino Turnip|2021|male
          12S21002|Marudut Tampubolon|2021|male
          12S21003|Jusas Tampubolon|2021|male
          12S21004|Estomihi pangaribuan|2021|male
          12S21006|Weny Sitinjak|2021|female
          12S21007|Dame Sitinjak|2021|female
          12S21008|Tuani Manurung|2021|male
          12S21009|Mikhael Pakpahan|2021|male
          12S21010|Bobby Siagian|2021|male
          12S21011|Aldi Simamora|2021|male
          Pniel|20|female
          Kapernaum|20|male
          Antiokia|20|male
          Mamre|20|male
          Silo|20|male
          Mahanaim|20|male
          Nazaret|20|male
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        T08-45-01-45-01_RESULTS: "${{steps.t08-45-01-45-01.outputs.result}}"
        T08-45-01-45-02_RESULTS: "${{steps.t08-45-01-45-02.outputs.result}}"
        T08-45-02-45-01_RESULTS: "${{steps.t08-45-02-45-01.outputs.result}}"
        T08-45-02-45-02_RESULTS: "${{steps.t08-45-02-45-02.outputs.result}}"
        T08-45-02-45-03_RESULTS: "${{steps.t08-45-02-45-03.outputs.result}}"
      with:
        runners: t08-45-01-45-01,t08-45-01-45-02,t08-45-02-45-01,t08-45-02-45-02,t08-45-02-45-03
